graph/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r"graphs", views.GraphViewSet)
router.register(r"graphpoints", views.GraphPointViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("graphs/", views.GraphListView.as_view()),
    path("graphs/<int:pk>", views.GraphDetailView.as_view(), name="graphs"),
    path("", views.IndexView.as_view()),
]

graphengine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("graphs/", include("graph.urls")),
    path("l4mbda/", include("l4mbda.urls")),
    path("calculus/", include("calculus.urls")),
    path("transformer/", include("transformer.urls")),
    path("k8smanager/", include("k8smanager.urls")),
    path("tagman/", include("tagman.urls")),
    path("llmtale/", include("llmtale.urls")),
    path("vecman/", include("vecman.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

l4mbda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("jobs/", views.JobView.as_view(), name="job_list"),
    path("jobruns/", views.JobRunView.as_view()),
    path("jobflow/", views.JobFlowView.as_view()),
    path("runjob/<int:pk>", views.JobRunnerView.as_view()),
    path("", views.IndexView.as_view()),
]

l4mbda/models.py
from django.db import models


class Job(models.Model):
    name = models.CharField(max_length=32, default="new job")
    code = models.TextField()
    times_to_run = models.IntegerField(default=1)

    # TODO should be in job run, race condition?
    storage = models.TextField(default="", null=True, blank=True)

    next_job = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return f"{self.name} {self.id}"

    def run(self):
        from l4mbda.tasks import run_job

        for _ in range(0, self.times_to_run):
            run_job.delay(self.id)
        return True

    def run_main(self):
        state = JobRun.objects.create(job=self)
        injected_globals = {}  # can restrict
        injected_locals = {"storage": self.storage}

        try:
            state.set_state("running")
            exec(self.code, injected_globals, injected_locals)
            self.storage = injected_locals["storage"]
            self.save()

            if self.next_job:
                self.next_job.storage = self.storage
                self.next_job.save()
                self.next_job.run_main()

            state.set_status("ok")
        except Exception as e:
            state.set_status("error")
            state.set_job_message(str(e))
        finally:
            state.set_state("done")


class JobRun(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    job_message = models.TextField(default="")

    state = models.CharField(
        max_length=16,
        default="not-run",
        choices=(("not-run", "not-run"), ("running", "running"), ("done", "done")),
    )

    status = models.CharField(
        max_length=16,
        default="none",
        choices=(("none", "none"), ("ok", "ok"), ("error", "error")),
    )

    def __str__(self):
        return f"{self.job.id} {self.state} {self.status}"

    def set_state(self, state):
        self.state = state
        self.save()

    def set_status(self, status):
        self.status = status
        self.save()

    def set_job_message(self, message):
        self.job_message = message
        self.save()


class JobInput(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.job.id}"

l4mbda/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import ListView, TemplateView
from django.views import View
from django.urls import reverse
from django.shortcuts import render
from .models import Job, JobRun


class IndexView(TemplateView):
    template_name = "l4mbda/index.html"


class JobView(ListView):
    model = Job


class JobRunView(ListView):
    model = JobRun


class JobRunnerView(View):
    def get(self, request, pk):
        job = Job.objects.get(pk=pk)
        job.run()
        return HttpResponseRedirect(reverse("job_list"))


class JobFlowView(View):
    def get(self, request):
        return render(request, "l4mbda/job_flow.html", {})

    def post(self, request):
        pass

l4mbda/templates/l4mbda/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
    <h1 class="display-4">L4mbda</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </p>
    </div>
{% endblock %}

l4mbda/templates/l4mbda/job_flow.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

l4mbda/templates/l4mbda/job_list.html
{% extends "base.html" %}

{% block content %}
  {% for job in object_list %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{job.name}} ({{job.id}})</h5>
        <p class="card-text"> 
          Times to run: {{job.times_to_run}}<br/>
          Total runs: {{job.jobrun_set.all.count}}<br/>
          Next function: {{job.next_job}}<br/>
          Storage: {{job.storage}}<br/>
        </p>
        <p class="card-text">
          <pre>{{job.code}}</pre>
        </p>
        <a href="/l4mbda/runjob/{{job.id}}" class="btn btn-primary">Run job</a>
      </div>
    </div>
  {% endfor %}
{% endblock %}