graph/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r"graphs", views.GraphViewSet)
router.register(r"graphpoints", views.GraphPointViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("graphs/", views.GraphListView.as_view()),
    path("graphs/<int:pk>", views.GraphDetailView.as_view(), name="graphs"),
    path("", views.IndexView.as_view()),
]

graphengine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("graphs/", include("graph.urls")),
    path("l4mbda/", include("l4mbda.urls")),
    path("calculus/", include("calculus.urls")),
    path("transformer/", include("transformer.urls")),
    path("k8smanager/", include("k8smanager.urls")),
    path("tagman/", include("tagman.urls")),
    path("llmtale/", include("llmtale.urls")),
    path("vecman/", include("vecman.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

llmtale/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("agents", views.LLMAgentListView.as_view(), name="agents"),
    path("agents/<int:pk>", views.LLMAgentView.as_view(), name="agent_detail"),
]

llmtale/models.py
from django.db import models


class Agent(models.Model):
    name = models.CharField(max_length=100)
    backstory = models.TextField()
    base_image = models.ImageField(upload_to="agents/")

    def __str__(self):
        return self.name

    def greeting(self):
        pass


class History(models.Model):
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    message = models.TextField()

llmtale/views.py
from django.views.generic import TemplateView, ListView
from django.views import View
from django.shortcuts import render
from . import models
from . import forms


class IndexView(TemplateView):
    template_name = "llmtale/index.html"


class LLMAgentListView(ListView):
    model = models.Agent
    template_name = "llmtale/llmagent_list.html"


class LLMAgentView(View):
    def get(self, request, pk):
        model = models.Agent.objects.get(pk=pk)
        form = forms.TextInputForm()
        return render(
            request, "llmtale/llmagent_detail.html", {"agent": model, "form": form}
        )

    def post(self, request, pk):
        model = models.Agent.objects.get(pk=pk)
        form = forms.TextInputForm(request.POST)
        if form.is_valid():
            pass

        return render(
            request, "llmtale/llmagent_detail.html", {"agent": model, "form": form}
        )

llmtale/templates/llmtale/index.html
{% extends "base.html" %}

{% block content %}
Hello
{% endblock %}

llmtale/templates/llmtale/llmagent_detail.html
{% extends "base.html" %}

{% block content %}
    <img src="{{ agent.base_image.url }}" alt="{{ agent.name }}" class="img-thumbnail">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
{% endblock %}

llmtale/templates/llmtale/llmagent_list.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    {% for agent in agent_list %}
        <h1> {{ agent.name }} </h1>
        <img src="{{ agent.base_image.url }}" alt="{{ agent.name }}" class="img-thumbnail">
        <a href="{% url 'agent_detail' agent.id %}">View</a>
    {% endfor %}
</div>

{% endblock %}